name: Smoke Test

on:
  push:
    branches:
      - stage

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: 'actions/checkout@v4'

      - name: Install dependencies
        run: npm install

      - name: Run smoke test
        run: npm run test