name: 'Staging Docker Registry Push'

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
          
      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="ghcr.io/rylero/jobcampstaging:latest"
          docker buildx build -f staging.Dockerfile --tag "${DOCKER_TAG}" --build-arg DATABASE_URL="${{ secrets.STAGING_DATABASE_URL }}" --build-arg MAILTRAP_TOKEN="${{ secrets.MAILTRAP_TOKEN }}" .
          docker push "${DOCKER_TAG}"


